/** RimWorld in-game date: 4 quadrums x 15 days = 60 day year. */
export interface RimWorldDate {
  day: number; // 1-15
  quadrumIndex: number; // 0-3 (Aprimay, Jugust, Septober, Decembary)
  year: number;
}

export type TemplateFieldType =
  | "colonist" // single colonist dropdown
  | "colonist-multi" // multi-select colonists (participants)
  | "faction" // faction dropdown
  | "location" // location dropdown
  | "slider" // numeric severity slider
  | "route" // route dropdown (world map)
  | "text" // short text input
  | "textarea"; // multiline text

export interface TemplateField {
  id: string; // placeholder key, e.g. "faction" -> {{faction}}
  label: string;
  type: TemplateFieldType;
  required?: boolean;
  placeholder?: string;
  default?: string | number | string[];
  // Slider config
  sliderMin?: number;
  sliderMax?: number;
  sliderStep?: number;
  sliderUnit?: string;
  mapsToIntensity?: boolean; // slider value scaled to intensityScore (1-10)
  derivesThreat?: boolean; // slider thresholds derive ThreatLevel
  threatThresholds?: { minor: number; moderate: number; major: number };
}

export interface EventTemplate {
  id: string;
  name: string; // "Raid"
  icon?: string; // lucide icon key (see components/Timeline/TemplateIcon.tsx)
  accent?: string; // color token: red/emerald/blue/amber/cyan/violet
  category: EventCategory;
  threatLevel: ThreatLevel; // base level; may be overridden by a deriving slider
  titleTemplate: string; // "{{faction}} Raid on {{location}}"
  descriptionTemplate: string; // markdown with {{field}} placeholders + [[auto-links]]
  impactTemplate?: string; // narrative fallout template
  fields: TemplateField[];
  custom?: boolean; // user-created (deletable); built-ins are false
}

export type ArticleCategory =
  | "Characters"
  | "Factions"
  | "Locations"
  | "Relics"
  | "Chronicles"
  | "Lore"
  | "Battles";

export interface WikiArticle {
  id: string;
  title: string;
  category: ArticleCategory;
  tags: string[];
  markdownContent: string;
  createdAt: string;
  lastModified: string;
  backlinks?: string[]; // list of other article IDs or titles referencing this
  wordCount?: number;
  featuredQuote?: string;
  infoboxData?: Record<string, string>;
}

export type CharacterStatus =
  | "Active"
  | "Injured"
  | "In Mental Break"
  | "Missing"
  | "Deceased"
  | "Transhumanist Ascended";

/**
 * Project-wide attribute slot configuration. Every character shares the same
 * slot layout; users rename/repurpose slots per mode (e.g. "Bionics" becomes
 * "Spells / Prepared" in Fantasy/TTRPG mode). Character values live in
 * Character.slotEntries keyed by slot id, so renaming never loses data.
 */
export interface AttributeSlotConfig {
  id: string; // stable key, e.g. "slot-a" — survives renames & mode switches
  label: string; // user-visible name
  /** Set once the user hand-renames a slot; blocks auto-relabel on mode switch. */
  customLabel?: boolean;
}

/** Structured numeric fields consumed by the Stat Block Renderer. */
export interface CombatStats {
  strength?: number;
  dexterity?: number;
  constitution?: number;
  intelligence?: number;
  wisdom?: number;
  charisma?: number;
  armorClass?: string;
  hitPoints?: string;
  speed?: string;
  initiative?: string;
  challengeRating?: string;
  creatureType?: string;
  senses?: string;
  languages?: string;
}

export interface Character {
  id: string;
  name: string;
  nickname: string;
  role: string;
  faction: string;
  status: CharacterStatus;
  traits: string[];
  healthConditions: string[];
  /**
   * Dynamic attribute slot values keyed by AttributeSlotConfig.id. Migrated
   * projects split legacy healthConditions into the seeded slots; the flat
   * healthConditions field remains as a derived mirror of all entries.
   */
  slotEntries?: Record<string, string[]>;
  combatStats?: CombatStats;
  bio: string;
  dramaticArc: string;
  quote?: string;
  avatarColor?: string;
  avatarIcon?: string;
}

export type FactionStance = "Allied" | "Hostile" | "Neutral" | "Player Colony";

export interface Faction {
  id: string;
  name: string;
  type: string;
  stance: FactionStance;
  ideology: string;
  leader?: string;
  description: string;
  settlementLocation?: string;
}

export type EventCategory =
  | "Combat"
  | "Social"
  | "Mental Break"
  | "Miracle"
  | "Quest"
  | "Tragedy"
  | "Discovery"
  | "Surgery"
  | "Colony Life"
  | "Travel";

export type ThreatLevel = "Minor" | "Moderate" | "Major" | "Catastrophic";

export interface TimelineEvent {
  id: string;
  timestamp: string; // e.g. "12 Aprimay, 5501"
  quadrumYear: string; // e.g. "Year 5501"
  title: string;
  category: EventCategory;
  threatLevel: ThreatLevel;
  participants: string[];
  location: string;
  description: string;
  narrativeImpact: string;
  linkedChapterId?: string;
  intensityScore?: number; // 1 to 10
  isDowntimeFiller?: boolean; // Generated by Downtime Dice as an off-screen beat
}

export type DowntimeFrequency = "every-other-day" | "daily" | "twice-daily" | "thrice-daily";

export interface DowntimeDiceSettings {
  frequency: DowntimeFrequency; // How many off-screen beats fire per in-game day
  defaultCount: number; // Snippets generated per roll (3-5)
}

export interface DowntimeColonistProfile {
  name: string;
  nickname?: string;
  role?: string;
  status: CharacterStatus;
  traits: string[];
  healthConditions: string[];
  bionics: string[]; // Extracted prosthetic/augmentation items from healthConditions
}

export interface DowntimeSnippet {
  title: string;
  offsetDays: number; // Days after the anchor date (0 = same day)
  category: EventCategory;
  threatLevel: ThreatLevel;
  location: string;
  participants: string[];
  description: string;
  narrativeImpact: string;
  intensityScore: number; // 1 to 10
}

export type LocationType =
  | "Colony Settlement"
  | "Mining Outpost"
  | "Battlefield & War Zone"
  | "Ancient Cryptosleep Ruins"
  | "Resource Deposit"
  | "Psychic Hotspot"
  | "Crashed Ship Hull"
  | "Trading Hub"
  | "Tribal Camp"
  | "Raider Fortress";

export type BiomeType =
  | "Glacial Ice Sheet"
  | "Tundra"
  | "Boreal Mountain Forest"
  | "Temperate Valley"
  | "Arid Shrubland"
  | "Desert Badlands"
  | "Toxic Swampland"
  | "Volcanic Ridge";

export interface CustomHexTile {
  q: number;
  r: number;
  biome: BiomeType;
  elevation: "Lowland" | "Hills" | "High Peaks" | "Canyon" | "Glacial Crest";
  movementCost: number; // e.g. 0.5 (Highway) to 3.0 (Extreme Rugged Mountain)
  isPassable?: boolean;
  roadType?: "None" | "Dirt Path" | "Stone Road" | "Ancient Asphalt Highway";
  feature?: "Geothermal Vent" | "Ancient Road" | "Frozen River" | "Defoliator Crater" | "Archotech Pillar" | "None";
  customLabel?: string;
}

export interface TerrainCostConfig {
  baseDaysPerHex: number; // default 0.85 days per standard 1.0 tile
  biomeCostDefaults: Record<BiomeType, number>;
  roadMultipliers: {
    none: number;
    dirtPath: number;
    stoneRoad: number;
    highway: number;
  };
  elevationMultipliers: {
    lowland: number;
    hills: number;
    highPeaks: number;
    canyon: number;
    glacialCrest: number;
  };
}

export interface LocationItem {
  id: string;
  name: string;
  type: string;
  dangerLevel: "Safe" | "Dangerous" | "Extreme Hazard";
  description: string;
  hexCoord?: { q: number; r: number };
  position?: { x: number; y: number }; // 0 to 100% on custom overlay
  biome?: BiomeType;
  terrainDifficulty?: number; // Movement multiplier: e.g. 1.0 standard, 1.8 rugged mountain, 0.7 road
  controllingFaction?: string;
  garrisonColonists?: string[];
  activeResources?: string[];
  elevationMeters?: number;
  temperatureCelsius?: number;
  linkedArticleId?: string;
}

export interface TravelHazard {
  id: string;
  label: string;
  severity: ThreatLevel;   // Minor / Moderate / Major / Catastrophic
  description?: string;
}

export interface MapRoute {
  id: string;
  sourceId: string;
  targetId: string;
  name: string;
  distanceHexes: number;
  terrainDifficultyAvg: number;
  travelDaysOnFoot: number;
  travelDaysMuffalo: number;
  travelDaysDropPods: number;
  travelDaysMechanoid: number;
  logisticalHazards: string[];
  hazards?: TravelHazard[];
  notes?: string;
}

export interface MapSettings {
  mapStyle: "hexGrid" | "customOverlay";
  themeTerrain: "glacier" | "temperate" | "arid" | "volcanic";
  customMapImageUrl?: string;
  gridCols: number;
  gridRows: number;
  showHeatmap: boolean;
  heatmapType: "all" | "warzones" | "psychic" | "caravan" | "casualties";
  showRoutes: boolean;
  showLabels: boolean;
  showCoordinates: boolean;
  showFactions: boolean;
  showMovementCosts?: boolean;
  editTileOnClick?: boolean;
  overlayOpacity?: number;
  customTiles?: Record<string, CustomHexTile>; // key: `${q},${r}`
  terrainCostConfig?: TerrainCostConfig;
  mapSkin?: "world" | "dungeon";
}

export interface RelicItem {
  id: string;
  name: string;
  category: string;
  wielder: string;
  description: string;
}

export type RelationshipType =
  | "Spouse"
  | "Romance"
  | "Rival"
  | "Blood Feud"
  | "Kin"
  | "Bonded Beast"
  | "Savior"
  | "Betrayer"
  | "Grudge"
  | "Mentor";

export interface CharacterRelationship {
  id: string;
  source: string; // Character Name or ID
  target: string; // Character Name or ID
  type: RelationshipType;
  opinion: number; // -100 to +100
  notes: string;
}

export interface StoryScene {
  id: string;
  title: string;
  description: string;
  assignedEventIds: string[];
  sceneMarkdown?: string;
  status: "Outline" | "Drafted" | "Polished";
}

export interface StoryChapter {
  id: string;
  title: string;
  summary: string;
  scenes: StoryScene[];
  fullChapterMarkdown?: string;
  wordCount?: number;
  isDrafted?: boolean;
}

export interface StoryAct {
  id: string;
  title: string;
  theme: string;
  chapters: StoryChapter[];
}

export interface CanonConstraint {
  id: string;
  title: string;
  ruleStatement: string;
  reminderMessage: string;
  keywords: string[];
  isEnabled: boolean;
}

export type PlotGapType =
  | "Contradiction"
  | "Missing Bridge"
  | "Unresolved Arc"
  | "Pacing Warning"
  | "Lore Mystery"
  | "Dead Link"
  | "Orphaned Article"
  | "Loner Character"
  | "Missing Appearance"
  | "Pending Draft"
  | "Unlinked Article"
  | "Ghost Event"
  | "Duplicate Article"
  | "Broken Faction Ref"
  | "Timeline Stagnation"
  | "Cultural Friction"
  | "Hazard Unprepared";

export type PlotGapSeverity = "Critical" | "Warning" | "Opportunity";

export interface PlotGap {
  id: string;
  type: PlotGapType;
  severity: PlotGapSeverity;
  title: string;
  affectedEntities: string[];
  explanation: string;
  suggestedBridge: string;
  recommendedChapterPlacement?: string;
  status: "open" | "resolved";
}

export interface PlotGapAnalysisReport {
  overallConsistencyScore: number;
  literaryToneAssessment: string;
  plotGaps: PlotGap[];
  novelizationTips: string[];
  analyzedAt?: string;
}

export type ThemeMode = "dark" | "parchment" | "cyber";

export interface StoryProject {
  id: string;
  title: string;
  subtitle: string;
  chronicleLogHistory: string[];
  wikiArticles: WikiArticle[];
  characters: Character[];
  factions: Faction[];
  timelineEvents: TimelineEvent[];
  locations: LocationItem[];
  relics: RelicItem[];
  relationships: CharacterRelationship[];
  storyHierarchy: StoryAct[];
  canonConstraints?: CanonConstraint[];
  /** Shared attribute slot layout (Bionics/Health/Skills in RimWorld mode,
   *  Spells/Feats/Saves/Inventory in Fantasy mode — user renameable). */
  attributeSlots?: AttributeSlotConfig[];
  mapRoutes?: MapRoute[];
  mapSettings?: MapSettings;
  plotGapReport?: PlotGapAnalysisReport;
  novelManuscript?: string;
  downtimeDiceSettings?: DowntimeDiceSettings;
  masterClock?: RimWorldDate; // Explicit colony date; falls back to latest event date when unset
  lastUpdated: string;
  preceptMatrices: PreceptMatrix[];
  culturalFrictionPoints: CulturalFrictionPoint[];
}

/* --------------------------- */
/* Precept Matrix Types        */
/* --------------------------- */

export type PreceptStance =
  | "Mandatory"
  | "Respected"
  | "Allowed"
  | "Disliked"
  | "Abhorred";

export type PreceptCategory =
  | "Body & Enhancement"
  | "Consumption & Cannibalism"
  | "Social Hierarchy"
  | "Nature & Ecology"
  | "Violence & War"
  | "Technology & AI"
  | "Death & Burial"
  | "Custom";

export interface PreceptTenet {
  id: string;
  key: string;
  label: string;
  description?: string;
  stance: PreceptStance;
  category: PreceptCategory;
  custom?: boolean;
}

export interface PreceptMatrix {
  factionId: string;
  factionName: string;
  tenets: PreceptTenet[];
  updatedAt: string;
}

export interface CulturalFrictionPoint {
  id: string;
  eventId: string;
  eventTitle: string;
  eventTimestamp: string;
  actionKey: string;
  actionLabel: string;
  primaryFactionId: string;
  primaryFactionStance: PreceptStance;
  opposingFactionId: string;
  opposingFactionStance: PreceptStance;
  severity: "Minor" | "Major" | "Critical";
  description: string;
  suggestedFallout: string;
  detectedAt: string;
  acknowledged: boolean;
}

export interface PreceptAction {
  label: string; // Free-text display label, e.g. "Branded the captured raiders"
  tenetKey: string; // Canonical tenet key compared by the engine, e.g. "slavery"
}

// Extend TimelineEvent with precept-related fields
export interface TimelineEvent {
  id: string;
  timestamp: string;
  quadrumYear: string;
  title: string;
  category: EventCategory;
  threatLevel: ThreatLevel;
  participants: string[];
  location: string;
  description: string;
  narrativeImpact: string;
  linkedChapterId?: string;
  intensityScore?: number;
  isDowntimeFiller?: boolean;
  // Free-form hazard/context tags (e.g. "venomous", "haunted") used by the
  // Plot Doctor's deterministic Hazard Unprepared check.
  tags?: string[];
  // Precept Matrix integration
  actions?: PreceptAction[];
  involvedFactionIds?: string[];
  frictionPoints?: CulturalFrictionPoint[];
}

/* --------------------------- */
/* ActiveTab                   */
/* --------------------------- */

export type ActiveTab =
  | "wiki"
  | "network"
  | "map"
  | "timeline"
  | "ideology"
  | "plotgap"
  | "novel"
  | "chronicler";

export interface CrossroadScenario {
  id: string;
  pathLabel: string; // "Path A", "Path B", "Path C"
  title: string; // e.g. "Mutiny Over Food Rations"
  summary: string; // 2-3 sentence overview
  triggerConditions: string; // What colony state makes this plausible
  keyParticipants: string[]; // Characters involved
  threatLevel: ThreatLevel;
  category: EventCategory;
  moodImpact: string; // How this shifts colony morale
  storyHook: string; // The dramatic question this raises
}

export interface CrossroadResult {
  colonySnapshot: {
    moodAverage: string;
    foodSupply: string;
    majorThreats: string[];
    recentTension: string;
  };
  scenarios: CrossroadScenario[];
  generatedAt: string;
}

export interface CrossroadDraft {
  scenarioId: string;
  openingSceneMarkdown: string; // Full drafted scene with [[WikiLinks]]
  dialoguePrompts: string[]; // 3-5 dialogue starters for key characters
  suggestedWikiUpdates: {
    articleTitle: string;
    updateSummary: string;
  }[];
  timelineEvent: {
    title: string;
    timestamp: string;
    category: EventCategory;
    threatLevel: ThreatLevel;
    participants: string[];
    location: string;
    description: string;
    narrativeImpact: string;
    intensityScore: number;
  };
}
